### ISSUE TITLE
Issues deploying `ovva_demo` variant to shinyapps.io

### ISSUE THREAD

**Issue by awosoga** [openvolley/ovva#4]
Potentially not an issue that you can address, but I’m working on a modified version of ovva but am not able to deploy it to shinyapps.io because of ovideo’s dependency on the `archive` package (used solely in [install_ffmpeg.R](https://github.com/openvolley/ovideo/blob/485ab4408facf6b8f18c90818a030eda9186d2d6/R/install_ffmpeg.R#L59)). An error is thrown that the shinyapps.io container image doesn’t have libarchive installed.

For example, something as simple as 

```
library(archive)
library(shiny)
ui <- fluidPage(
  plotOutput('plot')
)
server <- function(input, output) {
  output$plot <- renderPlot({
    hist(runif(200))
  })
}

shinyApp(ui = ui, server = server)
```

works fine locally but throws an error when I try to deploy it to shinyapps.io. So I’m wondering how [ovva_demo](https://openvolley.shinyapps.io/ovva_demo/) is able to run when it imports  `ovideo`, which in turn imports `archive`. Have you encountered this problem before? Or if this is a recent issue, when last did you deploy the ovva_demo? Would appreciate any insight that you have. Thanks,

**Comment by raymondben** [comment]
Last deploy of ovva_demo to shinyapps was prior to adding archive, so I didn't run across that issue. I was going to suggest raising an issue with Posit (like they tell you to do, when a system dependency is unavailable) ... but it does not look like they are overly responsive to issues or PRs there.
But we can avoid the archive dependency here, because `base::memDecompress` will handle .xz compression. I did not realize that previously, but just tried it and it seems fine, so I'll update ovideo in the next day or two.

**Comment by awosoga** [comment]
This is great news, thank you so much!

**Comment by raymondben** [comment]
ovideo updated: https://github.com/openvolley/ovideo/commit/14d80e1b476607dccbb1b7777b40a0f19399bd0e

- reinstall ovideo and see if that solves the deployment issue

**Comment by awosoga** [comment]
The error has resolved, thank you!
